### PR TITLE
Replace depricated erlang:now() with os:system_time()

### PR DESCRIPTION
**Pull request by yzh44yzh**
"erlang:now" is deprecated since OTP 18 and using it leads to compilation error in newer versions of erlang.

I add conditional compilation so library can be built with "erlang:now" for OTP 17, but with "os:system_time" for OTP 18 and higher. 

No need to change anything to build orca for OTP 17. Just run `rebar compile` as is was before. But you need to define macros "use_os_system_time" to build orca for OTP >= 18:
`./rebar compile -Duse_os_system_time`
(or use erl_opts for rebar3).

### CODE REVIEW

**Comment by yzh44yzh** [comment]
Tested with OTP 17.5, 18.3, 19.2

**Comment by yzh44yzh** [comment]
Works with rebar3 and erlang 19.2

```
{deps, [
    {orca, {git, "https://github.com/yzh44yzh/orca.git", {ref, "a01a3da7b2f7ccbcc7f6b1954da2b7334140168f"}}}
]}.

{overrides, [
    {override, orca, [
        {erl_opts, [{d, use_os_system_time}]}
    ]}
]}.
```
